### ISSUE TITLE
Add `data-bs-theme="light"` Attribute for Consistent Theme Handling in CSS

### ISSUE THREAD

**Issue by amrutadotorg** [lovasoa/SQLpage#369]
### Issue Description:
Hi,

It would be much easier to work with the CSS if we could add the `data-bs-theme="light"` attribute in the same way the `data-bs-theme="dark"` attribute has been added.

**Current Implementation:**

- **Light Theme:**
  ```html
  <body class="layout-boxed">
  ```

- **Dark Theme:**
  ```html
  <body class="layout-boxed" data-bs-theme="dark">
  ```

**Proposed Change:**

- **Light Theme:**
  ```html
  <body class="layout-boxed" data-bs-theme="light">
  ```

We should also make similar changes for other layouts to ensure consistency.

**Benefits:**

Once this change is implemented, accessing both themes in the CSS would be much easier. For example:

```css
body[data-bs-theme="dark"] #headline strong {
  background-color: #00E5FF; /* Bright cyan highlight background */
  color: #1C2833; /* Dark text for contrast */
  font-weight: bold;
  padding: 2px 4px; /* Optional: add padding to make the highlight more noticeable */
  border-radius: 3px; /* Optional: add border-radius for rounded corners */
}
```

This will allow for more efficient and maintainable theme-specific styling.

Thank you!
