### ISSUE TITLE
ERROR Configuration directory is not a valid directory

### ISSUE THREAD

**Issue by accforgithubtest** [lovasoa/SQLpage#589]
Switching the version from `lovasoa/sqlpage:v0.28.0` to `lovasoa/sqlpage:main` results in error which crashes the container.

Are there any expected breaking changes in the upcoming release ? Or are changes to existing configurations are needed before switching to main ?

Docker Compose
```
services:
  sqlpage:
    image: lovasoa/sqlpage:main
    container_name: sqlpage
    restart: always
    environment:
      DATABASE_URL: mysql://user:password@mysql:3306/testdb
      SQLPAGE_CONFIGURATION_DIRECTORY: /mnt/docker/volumes/sqlpage/sqlpage
    volumes:
      - /mnt/docker/volumes/sqlpage/stats:/var/www
      - /mnt/docker/volumes/sqlpage/sqlpage:/etc/sqlpage
    ports:
      - 8080
    depends_on:
      - mysql
    links:
      - mysql
```

Logs:
```
[2024-09-13T10:51:12.962Z ERROR sqlpage] Configuration directory is not a valid directory: "/mnt/docker/volumes/sqlpage/sqlpage"
Container stopped
```

### Version information

 - OS: Ubuntu 22.04 LTS
 - Database: MySQL
 - SQLPage Version : v0.28.0 (working fine) to main (broken)
