### ISSUE TITLE
web_root directory owned by root in Docker image

### ISSUE THREAD

**Issue by radarsymphony** [lovasoa/SQLpage#94]
Hi lovasoa,

This is a cool app! Thanks for making it available.

## Bug Description
I get a warning that the `current directory is not writeable` when I run a stock docker image:

```
sqlpage-app  | [2023-09-29T20:30:17Z WARN  sqlpage::app_config] No DATABASE_URL provided, and the current directory is not writeable. Using a temporary in-memory SQLite database. All the data created will be lost when this server shuts down.
sqlpage-app  | [2023-09-29T20:30:17Z INFO  sqlpage::webserver::database] Connecting to database: sqlite://:memory:
```

<details><summary>my docker-compose.yml</summary>

```
services:
  sqlpage-app:
    image: lovasoa/sqlpage:latest
    container_name: sqlpage-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.sqlpage-app.tls=true
      - traefik.http.routers.sqlpage-app.rule=Host(`sqlpage.example.com`)
      - traefik.http.routers.sqlpage-app.service=sqlpage-app
      - traefik.http.services.sqlpage-app.loadbalancer.server.port=8080
    environment:
      - TZ=America/Vancouver # doesn't change TZ...
        #- SQLPAGE_DATABASE_URL=sqlite://sqlpage.db?mode=rwc
        #- SQLPAGE_WEB_ROOT=/var/html
    #volumes:
      #- ./data/src:/var/www
    networks:
      - proxy

networks:
  proxy:
    external: true
```

</details>

## Expected Behavior
On start up, I think the docker image should create a new SQLite DB at sqlite://sqlpage.db, like this:

```
sqlpage-app  | [2023-09-29T20:08:06Z INFO  sqlpage::app_config] No DATABASE_URL provided, the current directory is writeable, creating sqlpage.db
sqlpage-app  | [2023-09-29T20:08:06Z INFO  sqlpage::webserver::database] Connecting to database: sqlite://sqlpage.db?mode=rwc
```

However, in the current latest release, the web_root `/var/www` is owned by `root:root` and so the `sqlpage` user cannot write to that directory.

## Potential Solutions
a) Pre-make the sqlite.db and set the ownership, then map the volume to the container
b) Modify the Dockerfile to change the ownership on startup (see below)
c) Another solution that is more aligned with your design philosophy. 

## Pull Request / Design options
I can resolve the issue by adding the following line to the Dockerfile and building an image:

```
RUN chown -R sqlpage:sqlpage /var/www
```

I've pushed my edit here: https://github.com/radarsymphony/SQLpage/commit/6c5fd8c4ae4cf28b3c33d6cec24d20989339b0c5

**However**, this approach will break when a different `web_root` is passed since the webroot is hardcoded in the Dockerfile.

Ideally, a startup script would:
- Integrate run-time environment variables like `(SQLPAGE_)WEB_ROOT`
- Change ownership on the web_root on startup.
- After all the setup, run `sqlpage` as the sqlpage user

What do you think? Is there another way around this? How does this affect the rest of the code base?

I am happy to have a go at a solution/startup script and then we can discuss. Let me know if I can help.
